# Tomcat
server:
    tomcat:
        uri-encoding: UTF-8
        max-threads: 1000
        min-spare-threads: 30
    port: 8282
    connection-timeout: 5000
    context-path: /aa

threadpool:
    core-pool-size: 100
    max-pool-size: 100
    queue-capacity: 10000
    keep-alive-seconds: 5000



spring:
    # 环境 dev|test|pro|系统默认使用dev
    profiles:
        active: dev
    # jackson时间格式化
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
    http:
        multipart:
            max-file-size: 2000MB
            max-request-size: 2000MB
            enabled: true
    resources: # 指定静态资源的路径
        static-locations: classpath:/static/,classpath:/views/

    application:
        name: spring-boot-rabbitmq

    rabbitmq:
        host: 172.16.16.127
        prot: 5672
        username: guest
        password: guest
        listener:
            concurrency: 10
            max-concurrency: 20
            prefetch: 5
